Repository GDSC-CAU/PuangFilm-BE, pull requests merged in 2024-08, with the labels that each got.

#13 [feat] Photo 모듈 관련 1차 구현 (#12)
  src/main/java/gdsc/cau/puangbe/common/util/ResponseCode.java
  src/main/java/gdsc/cau/puangbe/photo/controller/PhotoController.java
  src/main/java/gdsc/cau/puangbe/photo/dto/request/UploadImageDto.java
  src/main/java/gdsc/cau/puangbe/photo/entity/PhotoResult.java
  src/main/java/gdsc/cau/puangbe/photo/repository/PhotoRequestRepository.java
  src/main/java/gdsc/cau/puangbe/photo/repository/PhotoResultRepository.java
  src/main/java/gdsc/cau/puangbe/photo/service/PhotoService.java
  src/main/java/gdsc/cau/puangbe/photo/service/PhotoServiceImpl.java
Labels: feat

#17 [feat] photoRequest 비즈니스 로직 구현 (#14)
  src/main/java/gdsc/cau/puangbe/common/enums/Gender.java
  src/main/java/gdsc/cau/puangbe/common/exception/GlobalExceptionHandler.java
  src/main/java/gdsc/cau/puangbe/common/exception/PhotoException.java
  src/main/java/gdsc/cau/puangbe/common/exception/PhotoRequestException.java
  src/main/java/gdsc/cau/puangbe/common/exception/UserException.java
  src/main/java/gdsc/cau/puangbe/common/util/ResponseCode.java
  src/main/java/gdsc/cau/puangbe/photo/controller/PhotoController.java
  src/main/java/gdsc/cau/puangbe/photo/entity/PhotoOrigin.java
  src/main/java/gdsc/cau/puangbe/photo/entity/PhotoRequest.java
  src/main/java/gdsc/cau/puangbe/photo/entity/PhotoResult.java
  src/main/java/gdsc/cau/puangbe/photo/repository/PhotoRequestRepository.java
  src/main/java/gdsc/cau/puangbe/photo/repository/PhotoResultRepository.java
  src/main/java/gdsc/cau/puangbe/photo/service/PhotoServiceImpl.java
  src/main/java/gdsc/cau/puangbe/photorequest/controller/PhotoRequestController.java
  src/main/java/gdsc/cau/puangbe/photorequest/dto/CreateImageDto.java
  src/main/java/gdsc/cau/puangbe/photorequest/dto/ImageInfo.java
  src/main/java/gdsc/cau/puangbe/photorequest/dto/ResponseResultDto.java
  src/main/java/gdsc/cau/puangbe/photorequest/service/PhotoRequestService.java
  src/main/java/gdsc/cau/puangbe/photorequest/service/PhotoRequestServiceImpl.java
  src/main/java/gdsc/cau/puangbe/user/repository/UserRepository.java
Labels: chore, feat

#18 [test] 주요 비즈니스 로직 테스트코드 작성 및 Swagger 문서 구체화 (#15)
  build.gradle
  src/main/java/gdsc/cau/puangbe/common/config/RedisConfig.java
  src/main/java/gdsc/cau/puangbe/common/config/S3Config.java
  src/main/java/gdsc/cau/puangbe/common/exception/GlobalExceptionHandler.java
  src/main/java/gdsc/cau/puangbe/common/util/APIResponse.java
  src/main/java/gdsc/cau/puangbe/common/util/ApiResponse.java
  src/main/java/gdsc/cau/puangbe/photo/controller/PhotoController.java
  src/main/java/gdsc/cau/puangbe/photo/dto/request/UploadImageDto.java
  src/main/java/gdsc/cau/puangbe/photo/entity/PhotoRequest.java
  src/main/java/gdsc/cau/puangbe/photo/service/PhotoService.java
  src/main/java/gdsc/cau/puangbe/photo/service/PhotoServiceImpl.java
  src/main/java/gdsc/cau/puangbe/photorequest/controller/PhotoRequestController.java
  src/main/java/gdsc/cau/puangbe/photorequest/service/PhotoRequestService.java
  src/main/java/gdsc/cau/puangbe/photorequest/service/PhotoRequestServiceImpl.java
  src/main/java/gdsc/cau/puangbe/user/entity/User.java
  src/test/java/gdsc/cau/puangbe/photo/controller/PhotoControllerTest.java
  src/test/java/gdsc/cau/puangbe/photo/service/PhotoServiceImplTest.java
  src/test/java/gdsc/cau/puangbe/photorequest/controller/PhotoRequestControllerTest.java
  src/test/java/gdsc/cau/puangbe/photorequest/service/PhotoRequestServiceImplTest.java
Labels: chore, test

#21 [feat] 카카오 로그인 및 JWT 구현 (#6)
  .gradle/buildOutputCleanup/cache.properties
  build.gradle
  src/main/java/gdsc/cau/puangbe/PuangbeApplication.java
  src/main/java/gdsc/cau/puangbe/auth/config/CacheConfig.java
  src/main/java/gdsc/cau/puangbe/auth/config/JwtProperties.java
  src/main/java/gdsc/cau/puangbe/auth/config/KakaoLoginProperties.java
  src/main/java/gdsc/cau/puangbe/auth/controller/AuthController.java
  src/main/java/gdsc/cau/puangbe/auth/dto/KakaoIDTokenJWK.java
  src/main/java/gdsc/cau/puangbe/auth/dto/KakaoIDTokenPayload.java
  src/main/java/gdsc/cau/puangbe/auth/dto/KakaoIDTokenPublicKeyList.java
  src/main/java/gdsc/cau/puangbe/auth/dto/KakaoToken.java
  src/main/java/gdsc/cau/puangbe/auth/dto/LoginResponse.java
  src/main/java/gdsc/cau/puangbe/auth/dto/ReissueResponse.java
  src/main/java/gdsc/cau/puangbe/auth/entity/Token.java
  src/main/java/gdsc/cau/puangbe/auth/external/JwtProvider.java
  src/main/java/gdsc/cau/puangbe/auth/external/KakaoProvider.java
  src/main/java/gdsc/cau/puangbe/auth/external/OIDCProvider.java
  src/main/java/gdsc/cau/puangbe/auth/repository/TokenRepository.java
  src/main/java/gdsc/cau/puangbe/auth/service/AuthService.java
  src/main/java/gdsc/cau/puangbe/auth/service/AuthServiceImpl.java
  src/main/java/gdsc/cau/puangbe/common/exception/AuthException.java
  src/main/java/gdsc/cau/puangbe/common/exception/GlobalExceptionHandler.java
  src/main/java/gdsc/cau/puangbe/common/util/ResponseCode.java
  src/main/java/gdsc/cau/puangbe/user/entity/User.java
  src/main/java/gdsc/cau/puangbe/user/repository/UserRepository.java
Labels: fix, feat, style

#20 [feat] Redis 대기열 기능 및 이미지 결과 생성 과정 이관 (#19)
  src/main/java/gdsc/cau/puangbe/common/enums/RequestStatus.java
  src/main/java/gdsc/cau/puangbe/common/util/ConstantUtil.java
  src/main/java/gdsc/cau/puangbe/common/util/ResponseCode.java
  src/main/java/gdsc/cau/puangbe/photo/controller/PhotoController.java
  src/main/java/gdsc/cau/puangbe/photo/dto/request/UploadImageDto.java
  src/main/java/gdsc/cau/puangbe/photo/entity/PhotoRequest.java
  src/main/java/gdsc/cau/puangbe/photo/entity/PhotoResult.java
  src/main/java/gdsc/cau/puangbe/photo/service/PhotoService.java
  src/main/java/gdsc/cau/puangbe/photo/service/PhotoServiceImpl.java
  src/main/java/gdsc/cau/puangbe/photorequest/controller/PhotoRequestController.java
  src/main/java/gdsc/cau/puangbe/photorequest/dto/CreateImageDto.java
  src/main/java/gdsc/cau/puangbe/photorequest/dto/ImageInfo.java
  src/main/java/gdsc/cau/puangbe/photorequest/service/PhotoRequestServiceImpl.java
  src/main/java/gdsc/cau/puangbe/test/TestController.java
  src/main/java/gdsc/cau/puangbe/user/entity/User.java
  src/test/java/gdsc/cau/puangbe/photo/controller/PhotoControllerTest.java
  src/test/java/gdsc/cau/puangbe/photorequest/controller/PhotoRequestControllerTest.java
Labels: feat

#24 [feat] Argument Resolver 적용 (#23)
  src/main/java/gdsc/cau/puangbe/common/annotation/PuangUser.java
  src/main/java/gdsc/cau/puangbe/common/config/WebConfig.java
  src/main/java/gdsc/cau/puangbe/common/config/resolver/PuangUserArgumentResolver.java
Labels: feat

#25 [fix] 누락된 updateRequestDate 메서드 추가
  src/main/java/gdsc/cau/puangbe/user/entity/User.java
Labels: fix

#26 [infra] 배포 및 CI/CD 환경 구축 (#11)
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  Dockerfile
  build.gradle
Labels: infra

#28 [fix] API 엔드포인트 매개변수 및 표현 수정 (#27)
  .github/workflows/CI.yml
  src/main/java/gdsc/cau/puangbe/auth/controller/AuthController.java
  src/main/java/gdsc/cau/puangbe/common/config/SwaggerConfig.java
  src/main/java/gdsc/cau/puangbe/photo/controller/PhotoController.java
  src/main/java/gdsc/cau/puangbe/photo/dto/request/UploadImageDto.java
  src/main/java/gdsc/cau/puangbe/photorequest/controller/PhotoRequestController.java
  src/test/java/gdsc/cau/puangbe/photo/controller/PhotoControllerTest.java
  src/test/java/gdsc/cau/puangbe/photorequest/controller/PhotoRequestControllerTest.java
Labels: fix, test

#30 [feat] 이미지 완성 알림 이메일 발송 기능 구현 (#29)
  .github/workflows/CD.yml
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/checksums/md5-checksums.bin
  .gradle/8.8/checksums/sha1-checksums.bin
  build.gradle
  src/main/java/gdsc/cau/puangbe/common/util/ConstantUtil.java
  src/main/java/gdsc/cau/puangbe/common/util/ResponseCode.java
  src/main/java/gdsc/cau/puangbe/photo/dto/request/EmailInfo.java
  src/main/java/gdsc/cau/puangbe/photo/service/PhotoServiceImpl.java
  src/main/resources/templates/email-template.html
Labels: feat

#32 [fix] 이미지 처리 요청 생성 api/photo-request return 값 변경(#31)
  src/main/java/gdsc/cau/puangbe/photorequest/controller/PhotoRequestController.java
  src/main/java/gdsc/cau/puangbe/photorequest/service/PhotoRequestService.java
  src/main/java/gdsc/cau/puangbe/photorequest/service/PhotoRequestServiceImpl.java
Labels: fix, feat

#35 [feat] Spring RabbitMQ 설정 및 PhotoRequest Producer 생성 (#22)
  build.gradle
  src/main/java/gdsc/cau/puangbe/common/config/RabbitMq/RabbitMqConfig.java
  src/main/java/gdsc/cau/puangbe/common/config/RabbitMq/RabbitMqInfo.java
  src/main/java/gdsc/cau/puangbe/common/config/RabbitMq/RabbitMqProperties.java
  src/main/java/gdsc/cau/puangbe/photorequest/service/PhotoRequestServiceImpl.java
  src/main/java/gdsc/cau/puangbe/photorequest/service/RabbitMqService.java
  src/main/java/gdsc/cau/puangbe/photorequest/service/RabbitMqServiceImpl.java
Labels: feat

#37 [chore] 전반적인 코드 재정비 (#36)
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  src/main/java/gdsc/cau/puangbe/photo/service/PhotoServiceImpl.java
  src/main/java/gdsc/cau/puangbe/photorequest/service/PhotoRequestServiceImpl.java
  src/test/java/gdsc/cau/puangbe/PuangbeApplicationTests.java
  src/test/java/gdsc/cau/puangbe/photo/controller/PhotoControllerTest.java
  src/test/java/gdsc/cau/puangbe/photo/service/PhotoServiceImplTest.java
  src/test/java/gdsc/cau/puangbe/photorequest/controller/PhotoRequestControllerTest.java
  src/test/java/gdsc/cau/puangbe/photorequest/service/PhotoRequestServiceImplTest.java
Labels: chore, infra

#38 [feat] Redis를 이용한 Rate Limiter 적용 (#34)
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/checksums/md5-checksums.bin
  .gradle/8.8/checksums/sha1-checksums.bin
  build.gradle
  src/main/java/gdsc/cau/puangbe/common/config/RateLimiterConfig.java
  src/main/java/gdsc/cau/puangbe/common/config/RedisConfig.java
  src/main/java/gdsc/cau/puangbe/common/config/WebConfig.java
  src/main/java/gdsc/cau/puangbe/common/enums/RateLimitPolicy.java
  src/main/java/gdsc/cau/puangbe/common/exception/GlobalExceptionHandler.java
  src/main/java/gdsc/cau/puangbe/common/exception/RateLimiterException.java
  src/main/java/gdsc/cau/puangbe/common/interceptor/RateLimiterInterceptor.java
  src/main/java/gdsc/cau/puangbe/common/util/ResponseCode.java
Labels: feat

#40 [fix] RateLimiterInterceptor의 Authorization Header에 대한 Null 처리 (#39)
  src/main/java/gdsc/cau/puangbe/common/interceptor/RateLimiterInterceptor.java
Labels: fix

#42 [fix] auth의 누락된 예외 처리 및 Response Code 구체화
  src/main/java/gdsc/cau/puangbe/auth/external/JwtProvider.java
  src/main/java/gdsc/cau/puangbe/auth/external/KakaoProvider.java
  src/main/java/gdsc/cau/puangbe/auth/external/OIDCProvider.java
  src/main/java/gdsc/cau/puangbe/common/util/ResponseCode.java
Labels: fix

#44 [test] 실패하는 테스트코드 정상화 (#43)
  .github/workflows/CI.yml
  src/test/java/gdsc/cau/puangbe/photo/controller/PhotoControllerTest.java
  src/test/java/gdsc/cau/puangbe/photorequest/controller/PhotoRequestControllerTest.java
Labels: fix, test
