Repository GDSC-CAU/PuangFilm-BE, pull requests merged in 2024-07, with the labels that each got.

#2 [chore] MariaDB 및 Swagger 설정 (#1)
  .gitignore
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build.gradle
  src/main/java/gdsc/cau/puangbe/common/config/SwaggerConfig.java
  src/main/java/gdsc/cau/puangbe/test/TestController.java
  src/main/resources/application.properties
Labels: chore

#4 [feat] 1차 DB 테이블 구축 (#3)
  src/main/java/gdsc/cau/puangbe/common/enums/Gender.java
  src/main/java/gdsc/cau/puangbe/common/enums/RequestStatus.java
  src/main/java/gdsc/cau/puangbe/photo/entity/PhotoOrigin.java
  src/main/java/gdsc/cau/puangbe/photo/entity/PhotoRequest.java
  src/main/java/gdsc/cau/puangbe/photo/entity/PhotoResult.java
  src/main/java/gdsc/cau/puangbe/user/entity/User.java
Labels: feat

#5 [chore] Issue/PR 전용 템플릿 작성
  .github/ISSUE_TEMPLATE/기능-구현.md
  .github/ISSUE_TEMPLATE/버그-리포트.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#8 [fix] User의 gender값을 PhotoRequest로 이동 (#7)
  src/main/java/gdsc/cau/puangbe/photo/entity/PhotoRequest.java
  src/main/java/gdsc/cau/puangbe/user/entity/User.java
Labels: fix

#10 [feat] 커스텀 응답/예외 객체 및 GlobalExceptionHandler 설정 (#9)
  src/main/java/gdsc/cau/puangbe/common/exception/BaseException.java
  src/main/java/gdsc/cau/puangbe/common/exception/GlobalExceptionHandler.java
  src/main/java/gdsc/cau/puangbe/common/util/ApiResponse.java
  src/main/java/gdsc/cau/puangbe/common/util/ResponseCode.java
  src/main/java/gdsc/cau/puangbe/user/UserException.java
Labels: feat
